export const FETCH_COCKTAIL_START= "FETCH_COCKTAIL_START";
export const FETCH_COCKTAIL_SUCCESS= "FETCH_COCKTAIL_SUCCESS";
export const FETCH_COCKTAIL_FAIL= "FETCH_COCKTAIL_FAIL";
export const FETCH_SINGLE_COCKTAIL_START= "FETCH_SINGLE_COCKTAIL_START";
export const FETCH_SINGLE_COCKTAIL_SUCCESS= "FETCH_SINGLE_COCKTAIL_SUCCESS";
export const FETCH_SINGLE_COCKTAIL_FAIL= "FETCH_SINGLE_COCKTAIL_FAIL";